### ISSUE TITLE
Enable and configure dependabot

### ISSUE THREAD

**Issue by cflipse** [rubyforgood/stocks-in-the-future#7]

**Comment by jasonodoom** [comment]
I will commit the `dependabot.yml` but either @cflipse , @LizPrescott , @garettarrowood  or whomever else with admin privileges for this project should enable the below option(s).

![](https://github.blog/wp-content/uploads/2020/05/enable-automated-security-updates.gif?resize=1024%2C619)

**Comment by garettarrowood** [comment]
Looks like Github has moved around all of its settings. Here's what the dependabot settings look like. Perhaps it's on by default now? Unsure.

<img width="1147" alt="Screenshot 2023-08-01 at 8 33 23 AM" src="https://github.com/rubyforgood/stocks-in-the-future/assets/12770108/5ffe41dd-16b1-407d-b14f-56fa7eca2334">

**Comment by garettarrowood** [comment]
Actually - it's just in another spot. -- I've enabled it:

<img width="1227" alt="Screenshot 2023-08-01 at 8 36 38 AM" src="https://github.com/rubyforgood/stocks-in-the-future/assets/12770108/6ca8916c-820c-4d68-a2d3-229ec9f33110">

When I go to turn on it opening PRs on a weekly cadence, it prompts me with the ability to add a commit with the dependabot.yml file with this in it:

```
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
```

Adding that file may be what turns it on.
